# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://theochiu.github.io/
baseurl:
title: Theodore Chiu
author: Theodore Chiu
description: Personal blog and resume
avatar: githubprof.jpg
email: chiu42@purdue.edu
github: theochiu # username
# twitter: username
linkedin: theochiu
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
# disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
